import type { Detection, OriginalVideo, FingerprintInfo, RiskSummary, PropagationNode, MetricCard, ExplainabilityData } from './types'

export const mockOriginalVideo: OriginalVideo = {
  title: 'Advanced Neural Networks: Deep Learning Explained',
  thumbnailUrl: 'https://img.youtube.com/vi/aircAruvnKk/maxresdefault.jpg',
  duration: '19:14',
  resolution: '1080p',
  uploadedAt: '2024-03-15T14:30:00Z',
  platform: 'YouTube',
}

export const mockFingerprint: FingerprintInfo = {
  id: 'VFP-7A3F-9B2E-1C4D',
  framesAnalyzed: 47,
  model: 'CLIP ViT-B/32',
  createdAt: '2024-03-15T14:31:22Z',
}

export const mockRiskSummary: RiskSummary = {
  high: 4,
  medium: 3,
  low: 3,
}

export const mockDetections: Detection[] = [
  {
    id: 'd1',
    title: 'Neural Networks Explained - Full Course',
    channel: 'TechEduPro',
    thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    views: 2840000,
    similarity: 0.967,
    risk: 'high',
    platform: 'youtube',
    uploadedAt: '2024-03-17T08:15:00Z',
    duration: '18:45',
    url: 'https://youtube.com/watch?v=d1',
  },
  {
    id: 'd2',
    title: 'Deep Learning Complete Tutorial 2024',
    channel: 'CodeMasterHub',
    thumbnailUrl: 'https://img.youtube.com/vi/jGwO_UgTS7I/hqdefault.jpg',
    views: 1200000,
    similarity: 0.921,
    risk: 'high',
    platform: 'youtube',
    uploadedAt: '2024-03-18T11:30:00Z',
    duration: '20:12',
    url: 'https://youtube.com/watch?v=d2',
  },
  {
    id: 'd3',
    title: 'AI and Machine Learning for Beginners',
    channel: 'DigitalAcademy',
    thumbnailUrl: 'https://img.youtube.com/vi/ukzFI9rgwfU/hqdefault.jpg',
    views: 890000,
    similarity: 0.876,
    risk: 'high',
    platform: 'youtube',
    uploadedAt: '2024-03-19T14:00:00Z',
    duration: '22:08',
    url: 'https://youtube.com/watch?v=d3',
  },
  {
    id: 'd4',
    title: 'Understanding Backpropagation in Neural Nets',
    channel: 'MLInsights',
    thumbnailUrl: 'https://img.youtube.com/vi/Ilg3gGewQ5U/hqdefault.jpg',
    views: 445000,
    similarity: 0.812,
    risk: 'high',
    platform: 'youtube',
    uploadedAt: '2024-03-20T09:45:00Z',
    duration: '16:33',
    url: 'https://youtube.com/watch?v=d4',
  },
  {
    id: 'd5',
    title: 'Neural Network Fundamentals - Recap',
    channel: 'EduStream',
    thumbnailUrl: 'https://img.youtube.com/vi/OFS90-FX6pg/hqdefault.jpg',
    views: 312000,
    similarity: 0.748,
    risk: 'medium',
    platform: 'youtube',
    uploadedAt: '2024-03-21T16:20:00Z',
    duration: '14:51',
    url: 'https://youtube.com/watch?v=d5',
  },
  {
    id: 'd6',
    title: 'Deep Learning vs Machine Learning',
    channel: 'TechTalkDaily',
    thumbnailUrl: 'https://img.youtube.com/vi/l42lr8AlrHk/hqdefault.jpg',
    views: 220000,
    similarity: 0.714,
    risk: 'medium',
    platform: 'youtube',
    uploadedAt: '2024-03-22T10:00:00Z',
    duration: '12:44',
    url: 'https://youtube.com/watch?v=d6',
  },
  {
    id: 'd7',
    title: 'Introduction to AI Models',
    channel: 'LearnFast',
    thumbnailUrl: 'https://img.youtube.com/vi/R9OHn5ZF4Uo/hqdefault.jpg',
    views: 180000,
    similarity: 0.698,
    risk: 'medium',
    platform: 'youtube',
    uploadedAt: '2024-03-23T08:30:00Z',
    duration: '11:22',
    url: 'https://youtube.com/watch?v=d7',
  },
  {
    id: 'd8',
    title: 'Convolutional Neural Networks Explained',
    channel: 'DataSciHub',
    thumbnailUrl: 'https://img.youtube.com/vi/FmpDIaiMIeA/hqdefault.jpg',
    views: 95000,
    similarity: 0.612,
    risk: 'low',
    platform: 'youtube',
    uploadedAt: '2024-03-24T12:15:00Z',
    duration: '17:09',
    url: 'https://youtube.com/watch?v=d8',
  },
  {
    id: 'd9',
    title: 'AI Basics Every Developer Should Know',
    channel: 'DevWorld',
    thumbnailUrl: 'https://img.youtube.com/vi/GvYYFloV0aA/hqdefault.jpg',
    views: 67000,
    similarity: 0.589,
    risk: 'low',
    platform: 'youtube',
    uploadedAt: '2024-03-25T15:45:00Z',
    duration: '09:38',
    url: 'https://youtube.com/watch?v=d9',
  },
  {
    id: 'd10',
    title: 'Machine Learning Quick Overview',
    channel: 'QuickLearn',
    thumbnailUrl: 'https://img.youtube.com/vi/1vkb7BCMQd0/hqdefault.jpg',
    views: 42000,
    similarity: 0.534,
    risk: 'low',
    platform: 'youtube',
    uploadedAt: '2024-03-26T07:00:00Z',
    duration: '08:15',
    url: 'https://youtube.com/watch?v=d10',
  },
]

export const mockPropagationNodes: PropagationNode[] = [
  { id: 'original', title: 'Original Video', views: 850000, risk: 'low', similarity: 1.0, x: 50, y: 8, connections: ['d1', 'd2', 'd5'] },
  { id: 'd1', title: 'Neural Networks — Full Course', views: 2840000, risk: 'high', similarity: 0.967, x: 20, y: 35, connections: ['d3', 'd4'] },
  { id: 'd2', title: 'Deep Learning Tutorial', views: 1200000, risk: 'high', similarity: 0.921, x: 50, y: 35, connections: ['d6', 'd7'] },
  { id: 'd5', title: 'Neural Network Recap', views: 312000, risk: 'medium', similarity: 0.748, x: 80, y: 35, connections: ['d8'] },
  { id: 'd3', title: 'AI for Beginners', views: 890000, risk: 'high', similarity: 0.876, x: 12, y: 65, connections: [] },
  { id: 'd4', title: 'Backpropagation', views: 445000, risk: 'high', similarity: 0.812, x: 32, y: 65, connections: [] },
  { id: 'd6', title: 'Deep vs ML', views: 220000, risk: 'medium', similarity: 0.714, x: 48, y: 65, connections: ['d9'] },
  { id: 'd7', title: 'Intro to AI', views: 180000, risk: 'medium', similarity: 0.698, x: 65, y: 65, connections: [] },
  { id: 'd8', title: 'CNNs Explained', views: 95000, risk: 'low', similarity: 0.612, x: 82, y: 65, connections: ['d10'] },
  { id: 'd9', title: 'ML Overview', views: 67000, risk: 'low', similarity: 0.589, x: 52, y: 88, connections: [] },
  { id: 'd10', title: 'Quick Recap', views: 42000, risk: 'low', similarity: 0.534, x: 82, y: 88, connections: [] },
]

export const mockMetrics: MetricCard[] = [
  { label: 'Total Reach', value: '6.54M', change: '+12.4%', positive: false },
  { label: 'Total Views', value: '2.84M', change: '+8.1%', positive: false },
  { label: 'Engagement Rate', value: '4.7%', change: '+0.3%', positive: false },
  { label: 'Channels Affected', value: '10', change: '+2', positive: false },
]

export const mockExplainability: ExplainabilityData = {
  whyFlagged: [
    'Frame-level visual similarity exceeds 96% threshold',
    'Identical video structure detected across 4 keyframes',
    'Matching audio fingerprint in first 30 seconds',
    'Same resolution and aspect ratio (1080p 16:9)',
  ],
  visualSimilarity: 0.967,
  metadataSimilarity: 0.841,
  audioSimilarity: 0.912,
  confidence: 0.94,
}
